executable              = $(filename)
arguments               = $(Proxy_path) $(ClusterId)$(ProcId)
output                  = batchlogsnew2CnewF_TT_p_1.0/$(ClusterId).$(ProcId).out
error                   = batchlogsnew2CnewF_TT_p_1.0/$(ClusterId).$(ProcId).err
log                     = batchlogsnew2CnewF_TT_p_1.0/$(ClusterId).log
+JobFlavour = "workday"
x509userproxy = /afs/cern.ch/user/o/oyildiri/private/x509up_u188570

queue filename matching (execnew2CnewF_TT_p_1.0/job_*sh)
