executable              = $(filename)
arguments               = $(Proxy_path) $(ClusterId)$(ProcId)
output                  = batchlogsoldCnewF_TT/$(ClusterId).$(ProcId).out
error                   = batchlogsoldCnewF_TT/$(ClusterId).$(ProcId).err
log                     = batchlogsoldCnewF_TT/$(ClusterId).log
+JobFlavour = "workday"
x509userproxy = /afs/cern.ch/user/o/oyildiri/private/x509up_u188570

queue filename matching (execoldCnewF_TT/job_*sh)
