executable              = $(filename)
arguments               = $(Proxy_path) $(ClusterId)$(ProcId)
output                  = batchlogsnew2CnewF_Z_p_0.5/$(ClusterId).$(ProcId).out
error                   = batchlogsnew2CnewF_Z_p_0.5/$(ClusterId).$(ProcId).err
log                     = batchlogsnew2CnewF_Z_p_0.5/$(ClusterId).log
+JobFlavour = "workday"
x509userproxy = /afs/cern.ch/user/o/oyildiri/private/x509up_u188570

queue filename matching (execnew2CnewF_Z_p_0.5/job_*sh)
